name: upload gbatemp cheats

on:
  [push]

jobs:
  switch-cheats-db:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
      - name: install unrar
        run: sudo apt-get install unrar
      - name: run python script
        run: |
          python3 upload_cheats.py
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          echo $(hub --version)
          ls out
          gh release upload v1.0 ./out/contents.zip --clobber
          gh release upload v1.0 ./out/titles.zip --clobber
          hub release edit -m $(cat VERSION) -m "last updated the: $(cat DATE)" v1.0