name: update versions

on:
  schedule: 
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  switch-cheats-db:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install dependencies
        run: |
          if [ -f ./requirements_versions.txt ]; then pip3 install -r ./requirements_versions.txt; fi
      - name: run script
        run: |
          python3 -c 'from process_versions import ProcessVersions; ProcessVersions("https://raw.githubusercontent.com/blawar/titledb/master/cnmts.json").updateVersions()'
      - name: push changes
        run: |
          git config --global user.name 'HamletDuFromage'
          git config --global user.email '61667930+HamletDuFromage@users.noreply.github.com'
          git add versions.json
          git add versions.cbor
          git add versions/*
          if [[ `git status --porcelain` ]]; then
            git commit -m "automatic: updated version files"
            git push
          else
            echo "Nothing to commit!"
          fi
